name: Publish RC

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'The tag name to use'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps and package
        run: npm ci && npm run package
      - uses: JasonEtco/build-and-tag-action@v2
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
